#!/usr/bin/env python3
"""Render data/capability-matrix.v1.json into a static evidence site
(honua-io/honua-evidence#2, core deliverable).

Zero-dependency: Python standard library only (json, html, pathlib). Takes
no network access -- it renders whatever aggregate.py already wrote to
data/capability-matrix.v1.json. Run aggregate.py first.

Output: site/
  index.html                        all capabilities, filterable, receipts-first
  capabilities/<key-with-dashes>.html  one L2 page per capability
  data/capability-matrix.v1.json    JSON download (copy of the aggregate)
  freshness.html                    per-producer freshness ledger
  styles.css                        shared, plain, print-friendly

Status badge vocabulary is reused verbatim from honua-site's evidence pages
(data/capabilities.v1.json's statusVocabulary in honua-io/honua-site) so a
customer who has seen one recognizes the other:

  source-backed     green  "Source evaluation — counted evidence"
  source-evaluation  green  "Source evaluation"
  partial            amber  "Partial coverage"
  proof-pending      gray   "Proof pending"
"""
from __future__ import annotations

import argparse
import html
import json
import shutil
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = REPO_ROOT / "data" / "capability-matrix.v1.json"
DEFAULT_SITE_DIR = REPO_ROOT / "site"

STATUS_VOCAB = {
    "source-backed": {"badge": "green", "label": "Source evaluation — counted evidence"},
    "source-evaluation": {"badge": "green", "label": "Source evaluation"},
    "partial": {"badge": "amber", "label": "Partial coverage"},
    "proof-pending": {"badge": "gray", "label": "Proof pending"},
}

FRESHNESS_LABEL = {"fresh": "green", "stale": "amber", "missing": "gray"}

SOURCE_REPO_LINKS = {
    "server-keys": "https://github.com/honua-io/honua-server/blob/trunk/docs/gis/data/capability-keys.v1.json",
    "server-matrix": "https://github.com/honua-io/honua-server/blob/trunk/docs/gis/data/capability-matrix.v1.json",
    "sdk-js": "https://github.com/honua-io/honua-sdk-js/blob/trunk/config/sdk-coverage.v1.json",
    "sdk-dotnet": "https://github.com/honua-io/honua-sdk-dotnet/blob/trunk/contracts/sdk-coverage.v1.json",
    "sdk-python": "https://github.com/honua-io/honua-sdk-python/blob/trunk/compatibility/sdk-coverage.v1.json",
    "samples": "https://github.com/honua-io/honua-samples/actions/workflows/run-samples.yml",
    "open-issues": "https://github.com/honua-io/honua-server/issues?q=is%3Aopen+label%3Acap%2F%2A",
}


def esc(value: Any) -> str:
    return html.escape(str(value), quote=True)


def slug(key: str) -> str:
    return key.replace(".", "-")


def capability_status(cap: dict[str, Any]) -> str:
    if cap.get("entryCount", 0) > 0 and cap.get("provingTestCount", 0) > 0:
        return "source-backed"
    if cap.get("entryCount", 0) > 0:
        return "source-evaluation"
    if cap.get("noSurface") is not None:
        return "partial"
    return "proof-pending"


def sdk_status_badge(status: str | None) -> str:
    return {"covered": "green", "partial": "amber", "not-covered": "gray"}.get(status or "not-covered", "gray")


PAGE_HEAD = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>{title}</title>
<meta name="description" content="{description}" />
<link rel="stylesheet" href="{css_path}styles.css" />
</head>
<body>
<header class="site-header">
  <a class="brand" href="{root_path}index.html">honua-evidence</a>
  <p class="tagline">Every claim has a receipt. This is the receipts.</p>
  <nav>
    <a href="{root_path}index.html">Index</a>
    <a href="{root_path}freshness.html">Producer freshness</a>
    <a href="{root_path}data/capability-matrix.v1.json">Download JSON</a>
    <a href="https://github.com/honua-io/honua-evidence" target="_blank" rel="noopener noreferrer">Source ↗</a>
  </nav>
</header>
<main>
"""

PAGE_FOOT = """</main>
<footer class="site-footer">
  <p>Generated by <code>scripts/build-site.py</code> from <code>data/capability-matrix.v1.json</code>
  (<a href="{root_path}data/capability-matrix.v1.json">raw JSON</a>).
  Capability keys are owned by <a href="https://github.com/honua-io/honua-server" target="_blank" rel="noopener noreferrer">honua-server</a>, never redefined here.
  Generated at {generated_at}.</p>
</footer>
</body>
</html>
"""


def render_page(title: str, description: str, body: str, *, depth: int, generated_at: str) -> str:
    root_path = "../" * depth
    css_path = root_path
    head = PAGE_HEAD.format(title=esc(title), description=esc(description), css_path=css_path, root_path=root_path)
    foot = PAGE_FOOT.format(root_path=root_path, generated_at=esc(generated_at))
    return head + body + foot


def render_badge(status_key: str) -> str:
    entry = STATUS_VOCAB.get(status_key, STATUS_VOCAB["proof-pending"])
    return f'<span class="evidence-badge {entry["badge"]}">{esc(entry["label"])}</span>'


def render_freshness_badge(status: str) -> str:
    color = FRESHNESS_LABEL.get(status, "gray")
    return f'<span class="evidence-badge {color}">{esc(status)}</span>'


def render_index(matrix: dict[str, Any]) -> str:
    caps = matrix["capabilities"]
    by_category: dict[str, list[dict[str, Any]]] = {}
    for cap in caps:
        by_category.setdefault(cap["category"], []).append(cap)

    rows = []
    for cap in caps:
        status = capability_status(cap)
        sdk_summary = " ".join(
            f'<span class="sdk-chip {sdk_status_badge(cap["sdks"].get(sdk, {}).get("status"))}" title="{esc(sdk)}">{esc(sdk[:2].upper())}</span>'
            for sdk in ("js", "dotnet", "python")
        )
        sample_count = len(cap.get("samples", []))
        gap_count = cap.get("openIssues", {}).get("count", 0)
        rows.append(
            "<tr data-key=\"{key}\" data-category=\"{cat}\" data-edition=\"{ed}\" data-status=\"{status}\">"
            "<td class=\"cap-name\"><a href=\"capabilities/{slug}.html\">{name}</a><br/><code class=\"cap-key\">{key}</code></td>"
            "<td>{cat}</td><td><span class=\"edition-chip {ed_lower}\">{ed}</span></td>"
            "<td>{badge}</td>"
            "<td>{entry}/{tests}</td>"
            "<td>{sdks}</td>"
            "<td>{samples}</td>"
            "<td>{gaps}</td>"
            "</tr>".format(
                key=esc(cap["key"]),
                cat=esc(cap["category"]),
                ed=esc(cap["edition"]),
                ed_lower=esc(cap["edition"].lower()),
                status=esc(status),
                slug=slug(cap["key"]),
                name=esc(cap["displayName"]),
                badge=render_badge(status),
                entry=cap.get("entryCount", 0),
                tests=cap.get("provingTestCount", 0),
                sdks=sdk_summary,
                samples=sample_count,
                gaps=gap_count,
            )
        )

    total = len(caps)
    counts_by_status: dict[str, int] = {}
    for cap in caps:
        s = capability_status(cap)
        counts_by_status[s] = counts_by_status.get(s, 0) + 1

    summary_stats = "".join(
        f'<div class="stat"><div class="stat-num">{counts_by_status.get(k, 0)}</div>'
        f'<div class="stat-lbl">{esc(v["label"])}</div></div>'
        for k, v in STATUS_VOCAB.items()
    )

    category_options = "".join(f'<option value="{esc(c)}">{esc(c)}</option>' for c in sorted(by_category))

    body = f"""
<h1>Capability evidence index</h1>
<p class="lead">{total} capabilities, joined from honua-server's canonical capability vocabulary and enriched
with SDK coverage, executable samples, and known gaps. Every row links to a page that terminates
in a raw, independently checkable artifact.</p>

<div class="stats-row">{summary_stats}</div>

<div class="filter-bar">
  <input type="search" id="filter-text" placeholder="Filter by name or key…" aria-label="Filter capabilities by name or key" />
  <select id="filter-category" aria-label="Filter by category">
    <option value="">All categories</option>
    {category_options}
  </select>
  <select id="filter-edition" aria-label="Filter by edition">
    <option value="">All editions</option>
    <option value="Community">Community</option>
    <option value="Pro">Pro</option>
    <option value="Enterprise">Enterprise</option>
  </select>
  <select id="filter-status" aria-label="Filter by evidence status">
    <option value="">All statuses</option>
    <option value="source-backed">Source evaluation — counted evidence</option>
    <option value="source-evaluation">Source evaluation</option>
    <option value="partial">Partial coverage</option>
    <option value="proof-pending">Proof pending</option>
  </select>
</div>

<div class="table-wrap">
<table class="data-table" id="cap-table">
  <caption class="sr-only">All capabilities: category, edition, evidence status, counts, SDK coverage, samples, gaps</caption>
  <thead><tr>
    <th scope="col">Capability</th><th scope="col">Category</th><th scope="col">Edition</th>
    <th scope="col">Evidence</th><th scope="col">Entries/Tests</th><th scope="col">SDKs</th>
    <th scope="col">Samples</th><th scope="col">Gaps</th>
  </tr></thead>
  <tbody>{"".join(rows)}</tbody>
</table>
</div>
<p class="no-results" id="no-results" hidden>No capabilities match the current filters.</p>

<script>
(function () {{
  var text = document.getElementById('filter-text');
  var cat = document.getElementById('filter-category');
  var edition = document.getElementById('filter-edition');
  var status = document.getElementById('filter-status');
  var rows = Array.prototype.slice.call(document.querySelectorAll('#cap-table tbody tr'));
  var noResults = document.getElementById('no-results');

  function apply() {{
    var t = text.value.trim().toLowerCase();
    var visible = 0;
    rows.forEach(function (row) {{
      var matchesText = !t || row.dataset.key.toLowerCase().indexOf(t) !== -1 ||
        row.textContent.toLowerCase().indexOf(t) !== -1;
      var matchesCat = !cat.value || row.dataset.category === cat.value;
      var matchesEd = !edition.value || row.dataset.edition === edition.value;
      var matchesStatus = !status.value || row.dataset.status === status.value;
      var show = matchesText && matchesCat && matchesEd && matchesStatus;
      row.hidden = !show;
      if (show) visible++;
    }});
    noResults.hidden = visible !== 0;
  }}

  [text, cat, edition, status].forEach(function (el) {{ el.addEventListener('input', apply); }});
}})();
</script>
"""
    return body


def render_evidence_table(cap: dict[str, Any]) -> str:
    rows = []
    if cap.get("cite"):
        for entry in cap["cite"]:
            rows.append(
                f"<tr><td>CITE / conformance suite</td><td>{esc(entry.get('suite', ''))}"
                f" ({esc(entry.get('profile', ''))})</td>"
                f"<td>{esc(entry.get('passed', 0))}/{esc(entry.get('total', 0))} ({esc(entry.get('passRate', 0))}%)</td></tr>"
            )
    if cap.get("interop"):
        for entry in cap["interop"]:
            rows.append(
                f"<tr><td>Client interop</td><td>{esc(entry.get('clientLane', ''))} / {esc(entry.get('protocol', ''))}</td>"
                f"<td>certified lane (run dates not yet surfaced by this producer — remaining work, see #3)</td></tr>"
            )
    if cap.get("parity"):
        for entry in cap["parity"]:
            rows.append(
                f"<tr><td>Esri GeoServices REST parity</td><td>{esc(entry.get('displayName', entry.get('serviceId', '')))}</td>"
                f"<td>{esc(entry.get('parity', ''))}</td></tr>"
            )
    if cap.get("esriAssess"):
        rows.append(
            f"<tr><td>Esri migration assessment</td><td>assessKey(s)</td><td>{esc(', '.join(cap['esriAssess']))}</td></tr>"
        )
    if cap.get("geobench"):
        rows.append(
            f"<tr><td>Geobench scenario(s)</td><td>{esc(', '.join(cap['geobench']))}</td>"
            f"<td>scenario registered (p95 numbers not yet surfaced by this producer — remaining work, see #3)</td></tr>"
        )
    if cap.get("entryCount", 0) or cap.get("provingTestCount", 0):
        maturity = ", ".join(f"{k}: {v}" for k, v in (cap.get("maturity") or {}).items()) or "—"
        rows.append(
            f"<tr><td>Route entries &amp; proving tests</td><td>{esc(cap['entryCount'])} route entr"
            f"{'y' if cap['entryCount'] == 1 else 'ies'}</td>"
            f"<td>{esc(cap['provingTestCount'])} proving tests ({esc(maturity)})</td></tr>"
        )
    if cap.get("noSurface"):
        ns = cap["noSurface"]
        rows.append(
            f"<tr><td>No distinct route</td><td>{esc(ns.get('reasonCode', ''))}</td><td>{esc(ns.get('reason', ''))}</td></tr>"
        )
    if not rows:
        return '<p class="none">No evidence entries published for this capability yet.</p>'
    return (
        '<div class="table-wrap"><table class="data-table">'
        '<caption class="sr-only">Evidence by type</caption>'
        "<thead><tr><th scope=\"col\">Evidence type</th><th scope=\"col\">Detail</th><th scope=\"col\">Result</th></tr></thead>"
        f"<tbody>{''.join(rows)}</tbody></table></div>"
    )


def render_sdk_table(cap: dict[str, Any]) -> str:
    sdk_names = {"js": "honua-sdk-js", "dotnet": "honua-sdk-dotnet", "python": "honua-sdk-python"}
    rows = []
    for sdk, repo_name in sdk_names.items():
        entry = cap["sdks"].get(sdk, {"status": "not-covered"})
        status = entry.get("status", "not-covered")
        badge_color = sdk_status_badge(status)
        entrypoints = ", ".join(entry.get("entrypoints", [])[:4]) or "—"
        note = entry.get("note", "")
        rows.append(
            f"<tr><td><a href=\"https://github.com/honua-io/{repo_name}\" target=\"_blank\" rel=\"noopener noreferrer\">{esc(repo_name)}</a></td>"
            f"<td><span class=\"evidence-badge {badge_color}\">{esc(status)}</span></td>"
            f"<td>{esc(entrypoints)}</td>"
            f"<td>{esc(note) if note else '—'}</td></tr>"
        )
    return (
        '<div class="table-wrap"><table class="data-table">'
        '<caption class="sr-only">SDK coverage</caption>'
        "<thead><tr><th scope=\"col\">SDK</th><th scope=\"col\">Status</th><th scope=\"col\">Entry points</th><th scope=\"col\">Note</th></tr></thead>"
        f"<tbody>{''.join(rows)}</tbody></table></div>"
    )


def render_samples_table(cap: dict[str, Any]) -> str:
    samples = cap.get("samples", [])
    if not samples:
        return '<p class="none">No executable sample published for this capability yet.</p>'
    rows = []
    for s in samples:
        last_run = s.get("lastRun") or {}
        outcome = last_run.get("outcome", "unknown")
        rows.append(
            f"<tr><td><a href=\"{esc(s.get('url', '#'))}\" target=\"_blank\" rel=\"noopener noreferrer\">{esc(s.get('title', s.get('id', '')))}</a></td>"
            f"<td>{esc(', '.join(s.get('sdks', [])))}</td><td>{esc(s.get('edition', ''))}</td>"
            f"<td>{esc(outcome)} (server {esc(last_run.get('serverVersion', '?'))}, {esc(last_run.get('at', 'unknown date'))})</td></tr>"
        )
    return (
        '<div class="table-wrap"><table class="data-table">'
        '<caption class="sr-only">Executable samples</caption>'
        "<thead><tr><th scope=\"col\">Sample</th><th scope=\"col\">SDK lane</th><th scope=\"col\">Edition</th><th scope=\"col\">Last run</th></tr></thead>"
        f"<tbody>{''.join(rows)}</tbody></table></div>"
    )


def render_gaps(cap: dict[str, Any]) -> str:
    issues = cap.get("openIssues", {})
    refs = issues.get("refs", [])
    if not refs:
        return '<p class="none">No open honua-server issues tagged for this capability’s category.</p>'
    note = (
        '<p class="note">Gaps are currently attached at the <strong>category</strong> level '
        f'(<code>{esc(issues.get("label", ""))}</code> label), not the individual capability key '
        "— finer-grained per-capability mapping is remaining work (honua-io/honua-evidence#5).</p>"
    )
    items = "".join(
        f'<li><a href="{esc(ref["url"])}" target="_blank" rel="noopener noreferrer">#{esc(ref["number"])}</a> {esc(ref["title"])}</li>'
        for ref in refs
    )
    return note + f'<ul class="gaps-list">{items}</ul>'


def render_capability_page(cap: dict[str, Any], matrix: dict[str, Any], generated_at: str) -> str:
    status = capability_status(cap)
    body = f"""
<p class="lead"><a href="../index.html">← Back to the capability index</a></p>
<span class="eyebrow">{esc(cap['category'])} · {esc(cap['key'])}</span>
<h1>{esc(cap['displayName'])}</h1>
<p>{render_badge(status)} <span class="edition-chip {esc(cap['edition'].lower())}">{esc(cap['edition'])}</span></p>

<h2>Evidence by type</h2>
{render_evidence_table(cap)}

<h2>SDK coverage</h2>
{render_sdk_table(cap)}

<h2>Executable samples</h2>
{render_samples_table(cap)}

<h2>Known gaps</h2>
{render_gaps(cap)}

<h2>Raw receipts</h2>
<ul class="gaps-list">
  <li><a href="https://github.com/honua-io/honua-server/blob/trunk/docs/gis/data/capability-keys.v1.json" target="_blank" rel="noopener noreferrer">capability-keys.v1.json</a> — canonical key definition for <code>{esc(cap['key'])}</code>.</li>
  <li><a href="https://github.com/honua-io/honua-server/blob/trunk/docs/gis/data/capability-matrix.v1.json" target="_blank" rel="noopener noreferrer">capability-matrix.v1.json</a> — honua-server's Phase-A evidence snapshot (entry/test counts, CITE, parity, interop, geobench).</li>
  <li><a href="https://github.com/honua-io/honua-sdk-js/blob/trunk/config/sdk-coverage.v1.json" target="_blank" rel="noopener noreferrer">sdk-js coverage</a> ·
      <a href="https://github.com/honua-io/honua-sdk-dotnet/blob/trunk/contracts/sdk-coverage.v1.json" target="_blank" rel="noopener noreferrer">sdk-dotnet coverage</a> ·
      <a href="https://github.com/honua-io/honua-sdk-python/blob/trunk/compatibility/sdk-coverage.v1.json" target="_blank" rel="noopener noreferrer">sdk-python coverage</a></li>
  <li><a href="https://github.com/honua-io/honua-samples/actions/workflows/run-samples.yml" target="_blank" rel="noopener noreferrer">honua-samples run-samples CI</a> — executable sample run history.</li>
  <li><a href="../data/capability-matrix.v1.json">capability-matrix.v1.json</a> — the full enriched aggregate backing this page.</li>
</ul>
"""
    return render_page(
        title=f"Evidence: {cap['displayName']} | honua-evidence",
        description=f"Evidence detail for {cap['displayName']}: status, counts, SDK coverage, samples, gaps, and raw receipts.",
        body=body,
        depth=1,
        generated_at=generated_at,
    )


def render_freshness_page(matrix: dict[str, Any], generated_at: str) -> str:
    rows = []
    for name, entry in matrix.get("freshness", {}).items():
        link = SOURCE_REPO_LINKS.get(name, "#")
        rows.append(
            f"<tr><td><a href=\"{esc(link)}\" target=\"_blank\" rel=\"noopener noreferrer\">{esc(name)}</a></td>"
            f"<td>{render_freshness_badge(entry.get('status', 'missing'))}</td>"
            f"<td>{esc(entry.get('sourceVersion') or '—')}</td>"
            f"<td>{esc(entry.get('fetchedAt', ''))}</td>"
            f"<td>{esc(entry.get('detail', '') or '')}</td></tr>"
        )
    body = f"""
<p class="lead"><a href="index.html">← Back to the capability index</a></p>
<h1>Producer freshness ledger</h1>
<p>Every capability page's evidence is pulled from these producer snapshots. A producer that could not
be reached at build time is marked <strong>missing</strong>, never silently dropped; a producer whose
source is older than its staleness threshold is marked <strong>stale</strong>.</p>
<div class="table-wrap">
<table class="data-table">
  <caption class="sr-only">Per-producer freshness</caption>
  <thead><tr><th scope="col">Producer</th><th scope="col">Status</th><th scope="col">Source version</th><th scope="col">Fetched at</th><th scope="col">Detail</th></tr></thead>
  <tbody>{"".join(rows)}</tbody>
</table>
</div>
"""
    return render_page(
        title="Producer freshness | honua-evidence",
        description="Per-producer freshness ledger for the honua-evidence capability aggregate.",
        body=body,
        depth=0,
        generated_at=generated_at,
    )


CSS = """
:root {
  color-scheme: light dark;
  --text: #1a1f24; --text-dim: #55606a; --bg: #ffffff; --surface: #f4f6f8; --rule: #dbe1e6;
  --green-bg: rgba(95,196,166,0.16); --green-fg: #1c7a63;
  --amber-bg: rgba(217,130,74,0.18); --amber-fg: #9a5620;
  --gray-bg: #e7ebee; --gray-fg: #55606a;
}
@media (prefers-color-scheme: dark) {
  :root { --text: #e7ecef; --text-dim: #a9b4bc; --bg: #12161a; --surface: #1b2126; --rule: #2b333a;
    --green-bg: rgba(95,196,166,0.20); --green-fg: #7fe0c4;
    --amber-bg: rgba(217,130,74,0.22); --amber-fg: #f0aa6c;
    --gray-bg: #232b31; --gray-fg: #a9b4bc; }
}
:root[data-theme="dark"] { --text: #e7ecef; --text-dim: #a9b4bc; --bg: #12161a; --surface: #1b2126; --rule: #2b333a;
  --green-bg: rgba(95,196,166,0.20); --green-fg: #7fe0c4;
  --amber-bg: rgba(217,130,74,0.22); --amber-fg: #f0aa6c;
  --gray-bg: #232b31; --gray-fg: #a9b4bc; }
:root[data-theme="light"] { --text: #1a1f24; --text-dim: #55606a; --bg: #ffffff; --surface: #f4f6f8; --rule: #dbe1e6;
  --green-bg: rgba(95,196,166,0.16); --green-fg: #1c7a63;
  --amber-bg: rgba(217,130,74,0.18); --amber-fg: #9a5620;
  --gray-bg: #e7ebee; --gray-fg: #55606a; }

* { box-sizing: border-box; }
body { margin: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
  background: var(--bg); color: var(--text); line-height: 1.5; }
main { max-width: 1100px; margin: 0 auto; padding: 24px 20px 60px; }
a { color: inherit; }
code { font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace; font-size: 0.92em; }

.site-header { display: flex; flex-wrap: wrap; align-items: center; gap: 8px 20px; padding: 16px 20px;
  border-bottom: 1px solid var(--rule); max-width: 1100px; margin: 0 auto; }
.site-header .brand { font-weight: 700; font-size: 1.05rem; text-decoration: none; }
.site-header .tagline { color: var(--text-dim); font-size: 0.85rem; margin: 0; flex: 1 1 auto; }
.site-header nav { display: flex; gap: 14px; flex-wrap: wrap; font-size: 0.9rem; }
.site-header nav a { text-decoration: none; border-bottom: 1px solid transparent; }
.site-header nav a:hover { border-color: currentColor; }

.site-footer { max-width: 1100px; margin: 40px auto 0; padding: 16px 20px; border-top: 1px solid var(--rule);
  color: var(--text-dim); font-size: 0.82rem; }

.eyebrow { text-transform: uppercase; letter-spacing: 0.08em; font-size: 0.75rem; color: var(--text-dim); }
.lead { color: var(--text-dim); }
.none { color: var(--text-dim); font-style: italic; }
.note { border-left: 3px solid var(--amber-fg); background: var(--surface); padding: 10px 14px; border-radius: 0 6px 6px 0; }

.stats-row { display: flex; flex-wrap: wrap; gap: 12px; margin: 20px 0; }
.stat { border: 1px solid var(--rule); border-radius: 8px; padding: 12px 16px; background: var(--surface); min-width: 140px; }
.stat-num { font-size: 1.6rem; font-weight: 700; }
.stat-lbl { font-size: 0.78rem; color: var(--text-dim); }

.filter-bar { display: flex; flex-wrap: wrap; gap: 10px; margin: 20px 0; }
.filter-bar input, .filter-bar select { padding: 8px 10px; border: 1px solid var(--rule); border-radius: 6px;
  background: var(--bg); color: var(--text); font-size: 0.9rem; }
.filter-bar input { flex: 1 1 220px; }

.table-wrap { overflow-x: auto; margin: 14px 0 26px; border: 1px solid var(--rule); border-radius: 8px; }
table.data-table { border-collapse: collapse; width: 100%; font-size: 0.88rem; }
table.data-table th, table.data-table td { padding: 9px 12px; border-bottom: 1px solid var(--rule); text-align: left; vertical-align: top; }
table.data-table thead th { background: var(--surface); position: sticky; top: 0; }
table.data-table tbody tr:last-child td { border-bottom: none; }
.cap-key { color: var(--text-dim); font-size: 0.78rem; }
.no-results { color: var(--text-dim); font-style: italic; }

.evidence-badge { display: inline-block; padding: 2px 9px; border-radius: 999px; font-size: 0.72rem;
  letter-spacing: 0.04em; text-transform: uppercase; font-weight: 600; }
.evidence-badge.green { background: var(--green-bg); color: var(--green-fg); }
.evidence-badge.amber { background: var(--amber-bg); color: var(--amber-fg); }
.evidence-badge.gray { background: var(--gray-bg); color: var(--gray-fg); }

.edition-chip { display: inline-block; padding: 2px 9px; border-radius: 999px; font-size: 0.72rem; border: 1px solid var(--rule); }

.sdk-chip { display: inline-block; padding: 1px 6px; border-radius: 4px; font-size: 0.68rem; margin-right: 3px; font-weight: 700; }
.sdk-chip.green { background: var(--green-bg); color: var(--green-fg); }
.sdk-chip.amber { background: var(--amber-bg); color: var(--amber-fg); }
.sdk-chip.gray { background: var(--gray-bg); color: var(--gray-fg); }

.gaps-list { padding-left: 20px; }
.sr-only { position: absolute; width: 1px; height: 1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; }

@media print {
  .site-header nav, .filter-bar, .site-footer { display: none; }
  body { color: #000; background: #fff; }
  a[href^="http"]::after { content: " (" attr(href) ")"; font-size: 0.7em; color: #444; }
  .evidence-badge, .edition-chip, .sdk-chip { border: 1px solid #000; background: none !important; color: #000 !important; }
}
"""


def write_domain_files(site_dir):
    (site_dir / "CNAME").write_text("evidence.honua.io\n", encoding="utf-8")
    (site_dir / ".nojekyll").write_text("", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_SITE_DIR)
    args = parser.parse_args()

    if not args.input.exists():
        print(f"::error::{args.input} does not exist; run scripts/aggregate.py first.")
        return 1

    matrix = json.loads(args.input.read_text(encoding="utf-8"))
    generated_at = matrix.get("generatedAt", "unknown")

    if args.output.exists():
        shutil.rmtree(args.output)
    (args.output / "capabilities").mkdir(parents=True, exist_ok=True)
    (args.output / "data").mkdir(parents=True, exist_ok=True)

    (args.output / "styles.css").write_text(CSS.strip() + "\n", encoding="utf-8")
    shutil.copyfile(args.input, args.output / "data" / "capability-matrix.v1.json")

    index_body = render_index(matrix)
    index_html = render_page(
        title="honua-evidence — capability evidence index",
        description="Browsable index of Honua's capability evidence: entry counts, proving tests, CITE conformance, SDK coverage, executable samples, and known gaps, every claim linked to a raw artifact.",
        body=index_body,
        depth=0,
        generated_at=generated_at,
    )
    (args.output / "index.html").write_text(index_html, encoding="utf-8")

    (args.output / "freshness.html").write_text(
        render_freshness_page(matrix, generated_at), encoding="utf-8"
    )

    for cap in matrix["capabilities"]:
        page = render_capability_page(cap, matrix, generated_at)
        (args.output / "capabilities" / f"{slug(cap['key'])}.html").write_text(page, encoding="utf-8")

    page_count = 2 + len(matrix["capabilities"])  # index + freshness + one per capability
    write_domain_files(args.output)
    print(f"Built {page_count} pages ({len(matrix['capabilities'])} capabilities) into {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
